generatorName: python
additionalProperties:
  packageName: artifacts_mmo_client
  projectName: artifacts_mmo_client
  oseg.propertyNamingConvention: camel_case
  oseg.security.HTTPBasic.username: YOUR_USERNAME
  oseg.security.HTTPBasic.password: YOUR_PASSWORD
  oseg.security.JWTBearer.access_token: YOUR_ACCESS_TOKEN
