/*
 * Redocly Museum API
 *
 * Imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: team@redocly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPIMuseum.Client;
using Org.OpenAPIMuseum.Model;

namespace Org.OpenAPIMuseum.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEventsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// New special event added
        /// </summary>
        /// <remarks>
        /// Publish details of a new or updated event.
        /// </remarks>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="specialEvent"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void PublishNewEvent(SpecialEvent? specialEvent = default(SpecialEvent?), int operationIndex = 0);

        /// <summary>
        /// New special event added
        /// </summary>
        /// <remarks>
        /// Publish details of a new or updated event.
        /// </remarks>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="specialEvent"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PublishNewEventWithHttpInfo(SpecialEvent? specialEvent = default(SpecialEvent?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEventsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// New special event added
        /// </summary>
        /// <remarks>
        /// Publish details of a new or updated event.
        /// </remarks>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="specialEvent"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PublishNewEventAsync(SpecialEvent? specialEvent = default(SpecialEvent?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// New special event added
        /// </summary>
        /// <remarks>
        /// Publish details of a new or updated event.
        /// </remarks>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="specialEvent"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PublishNewEventWithHttpInfoAsync(SpecialEvent? specialEvent = default(SpecialEvent?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEventsApi : IEventsApiSync, IEventsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EventsApi : IEventsApi
    {
        private Org.OpenAPIMuseum.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EventsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EventsApi(string basePath)
        {
            this.Configuration = Org.OpenAPIMuseum.Client.Configuration.MergeConfigurations(
                Org.OpenAPIMuseum.Client.GlobalConfiguration.Instance,
                new Org.OpenAPIMuseum.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPIMuseum.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPIMuseum.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPIMuseum.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EventsApi(Org.OpenAPIMuseum.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPIMuseum.Client.Configuration.MergeConfigurations(
                Org.OpenAPIMuseum.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPIMuseum.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPIMuseum.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPIMuseum.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public EventsApi(Org.OpenAPIMuseum.Client.ISynchronousClient client, Org.OpenAPIMuseum.Client.IAsynchronousClient asyncClient, Org.OpenAPIMuseum.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPIMuseum.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPIMuseum.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPIMuseum.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPIMuseum.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPIMuseum.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// New special event added Publish details of a new or updated event.
        /// </summary>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="specialEvent"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void PublishNewEvent(SpecialEvent? specialEvent = default(SpecialEvent?), int operationIndex = 0)
        {
            PublishNewEventWithHttpInfo(specialEvent);
        }

        /// <summary>
        /// New special event added Publish details of a new or updated event.
        /// </summary>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="specialEvent"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPIMuseum.Client.ApiResponse<Object> PublishNewEventWithHttpInfo(SpecialEvent? specialEvent = default(SpecialEvent?), int operationIndex = 0)
        {
            Org.OpenAPIMuseum.Client.RequestOptions localVarRequestOptions = new Org.OpenAPIMuseum.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Org.OpenAPIMuseum.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPIMuseum.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = specialEvent;

            localVarRequestOptions.Operation = "EventsApi.PublishNewEvent";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (MuseumPlaceholderAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Org.OpenAPIMuseum.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/publishNewEvent", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublishNewEvent", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// New special event added Publish details of a new or updated event.
        /// </summary>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="specialEvent"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PublishNewEventAsync(SpecialEvent? specialEvent = default(SpecialEvent?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await PublishNewEventWithHttpInfoAsync(specialEvent, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// New special event added Publish details of a new or updated event.
        /// </summary>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="specialEvent"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPIMuseum.Client.ApiResponse<Object>> PublishNewEventWithHttpInfoAsync(SpecialEvent? specialEvent = default(SpecialEvent?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Org.OpenAPIMuseum.Client.RequestOptions localVarRequestOptions = new Org.OpenAPIMuseum.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Org.OpenAPIMuseum.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPIMuseum.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = specialEvent;

            localVarRequestOptions.Operation = "EventsApi.PublishNewEvent";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (MuseumPlaceholderAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Org.OpenAPIMuseum.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/publishNewEvent", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PublishNewEvent", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
