# coding: utf-8

# flake8: noqa
"""
    Redocly Museum API

    Imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.

    The version of the OpenAPI document: 1.2.1
    Contact: team@redocly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapimuseum_client.models.buy_museum_tickets import BuyMuseumTickets
from openapimuseum_client.models.error import Error
from openapimuseum_client.models.museum_daily_hours import MuseumDailyHours
from openapimuseum_client.models.museum_tickets_confirmation import MuseumTicketsConfirmation
from openapimuseum_client.models.special_event import SpecialEvent
from openapimuseum_client.models.special_event_fields import SpecialEventFields
from openapimuseum_client.models.ticket import Ticket
from openapimuseum_client.models.ticket_type import TicketType
