/*
 * Redocly Museum API
 * Imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: team@redocly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapimuseum.client.api;

import org.openapimuseum.client.ApiCallback;
import org.openapimuseum.client.ApiClient;
import org.openapimuseum.client.ApiException;
import org.openapimuseum.client.ApiResponse;
import org.openapimuseum.client.Configuration;
import org.openapimuseum.client.Pair;
import org.openapimuseum.client.ProgressRequestBody;
import org.openapimuseum.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapimuseum.client.model.Error;
import java.time.LocalDate;
import org.openapimuseum.client.model.MuseumDailyHours;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OperationsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OperationsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OperationsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getMuseumHours
     * @param startDate Starting date to retrieve future operating hours from. Defaults to today&#39;s date. (optional)
     * @param page Page number to retrieve. (optional, default to 1)
     * @param limit Number of days per page. (optional, default to 10)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getMuseumHoursCall(LocalDate startDate, Integer page, Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/museum-hours";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (startDate != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("startDate", startDate));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "MuseumPlaceholderAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getMuseumHoursValidateBeforeCall(LocalDate startDate, Integer page, Integer limit, final ApiCallback _callback) throws ApiException {
        return getMuseumHoursCall(startDate, page, limit, _callback);

    }

    /**
     * Get museum hours
     * Get upcoming museum operating hours.
     * @param startDate Starting date to retrieve future operating hours from. Defaults to today&#39;s date. (optional)
     * @param page Page number to retrieve. (optional, default to 1)
     * @param limit Number of days per page. (optional, default to 10)
     * @return List&lt;MuseumDailyHours&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public List<MuseumDailyHours> getMuseumHours(LocalDate startDate, Integer page, Integer limit) throws ApiException {
        ApiResponse<List<MuseumDailyHours>> localVarResp = getMuseumHoursWithHttpInfo(startDate, page, limit);
        return localVarResp.getData();
    }

    /**
     * Get museum hours
     * Get upcoming museum operating hours.
     * @param startDate Starting date to retrieve future operating hours from. Defaults to today&#39;s date. (optional)
     * @param page Page number to retrieve. (optional, default to 1)
     * @param limit Number of days per page. (optional, default to 10)
     * @return ApiResponse&lt;List&lt;MuseumDailyHours&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<MuseumDailyHours>> getMuseumHoursWithHttpInfo(LocalDate startDate, Integer page, Integer limit) throws ApiException {
        okhttp3.Call localVarCall = getMuseumHoursValidateBeforeCall(startDate, page, limit, null);
        Type localVarReturnType = new TypeToken<List<MuseumDailyHours>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get museum hours (asynchronously)
     * Get upcoming museum operating hours.
     * @param startDate Starting date to retrieve future operating hours from. Defaults to today&#39;s date. (optional)
     * @param page Page number to retrieve. (optional, default to 1)
     * @param limit Number of days per page. (optional, default to 10)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getMuseumHoursAsync(LocalDate startDate, Integer page, Integer limit, final ApiCallback<List<MuseumDailyHours>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getMuseumHoursValidateBeforeCall(startDate, page, limit, _callback);
        Type localVarReturnType = new TypeToken<List<MuseumDailyHours>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
