/*
 * Redocly Museum API
 *
 * Imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: team@redocly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPIMuseum.Client.OpenAPIDateConverter;

namespace Org.OpenAPIMuseum.Model
{
    /// <summary>
    /// Details for a museum ticket after a successful purchase.
    /// </summary>
    [DataContract(Name = "MuseumTicketsConfirmation")]
    public partial class MuseumTicketsConfirmation : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets TicketType
        /// </summary>
        [DataMember(Name = "ticketType", IsRequired = true, EmitDefaultValue = true)]
        public TicketType TicketType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MuseumTicketsConfirmation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MuseumTicketsConfirmation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MuseumTicketsConfirmation" /> class.
        /// </summary>
        /// <param name="ticketId">Unique identifier for museum ticket. Generated when purchased..</param>
        /// <param name="ticketDate">ticketDate (required).</param>
        /// <param name="ticketType">ticketType (required).</param>
        /// <param name="eventId">Identifier for a special event..</param>
        /// <param name="message">Confirmation message after a ticket purchase. (required).</param>
        /// <param name="confirmationCode">Unique confirmation code used to verify ticket purchase. (required).</param>
        public MuseumTicketsConfirmation(Guid ticketId = default(Guid), DateOnly ticketDate = default(DateOnly), TicketType ticketType = default(TicketType), Guid eventId = default(Guid), string message = default(string), string confirmationCode = default(string))
        {
            this.TicketDate = ticketDate;
            this.TicketType = ticketType;
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for MuseumTicketsConfirmation and cannot be null");
            }
            this.Message = message;
            // to ensure "confirmationCode" is required (not null)
            if (confirmationCode == null)
            {
                throw new ArgumentNullException("confirmationCode is a required property for MuseumTicketsConfirmation and cannot be null");
            }
            this.ConfirmationCode = confirmationCode;
            this.TicketId = ticketId;
            this.EventId = eventId;
        }

        /// <summary>
        /// Unique identifier for museum ticket. Generated when purchased.
        /// </summary>
        /// <value>Unique identifier for museum ticket. Generated when purchased.</value>
        /*
        <example>a54a57ca-36f8-421b-a6b4-2e8f26858a4c</example>
        */
        [DataMember(Name = "ticketId", EmitDefaultValue = false)]
        public Guid TicketId { get; set; }

        /// <summary>
        /// Gets or Sets TicketDate
        /// </summary>
        /*
        <example>2023-10-29</example>
        */
        [DataMember(Name = "ticketDate", IsRequired = true, EmitDefaultValue = true)]
        public DateOnly TicketDate { get; set; }

        /// <summary>
        /// Identifier for a special event.
        /// </summary>
        /// <value>Identifier for a special event.</value>
        /*
        <example>3be6453c-03eb-4357-ae5a-984a0e574a54</example>
        */
        [DataMember(Name = "eventId", EmitDefaultValue = false)]
        public Guid EventId { get; set; }

        /// <summary>
        /// Confirmation message after a ticket purchase.
        /// </summary>
        /// <value>Confirmation message after a ticket purchase.</value>
        /*
        <example>Museum general entry ticket purchased</example>
        */
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Unique confirmation code used to verify ticket purchase.
        /// </summary>
        /// <value>Unique confirmation code used to verify ticket purchase.</value>
        /*
        <example>ticket-event-a98c8f-7eb12</example>
        */
        [DataMember(Name = "confirmationCode", IsRequired = true, EmitDefaultValue = true)]
        public string ConfirmationCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MuseumTicketsConfirmation {\n");
            sb.Append("  TicketId: ").Append(TicketId).Append("\n");
            sb.Append("  TicketDate: ").Append(TicketDate).Append("\n");
            sb.Append("  TicketType: ").Append(TicketType).Append("\n");
            sb.Append("  EventId: ").Append(EventId).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  ConfirmationCode: ").Append(ConfirmationCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
