/*
 * Redocly Museum API
 *
 * Imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: team@redocly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPIMuseum.Client.OpenAPIDateConverter;

namespace Org.OpenAPIMuseum.Model
{
    /// <summary>
    /// Type of ticket being purchased. Use &#x60;general&#x60; for regular museum entry and &#x60;event&#x60; for tickets to special events.
    /// </summary>
    /// <value>Type of ticket being purchased. Use &#x60;general&#x60; for regular museum entry and &#x60;event&#x60; for tickets to special events.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TicketType
    {
        /// <summary>
        /// Enum Event for value: event
        /// </summary>
        [EnumMember(Value = "event")]
        Event = 1,

        /// <summary>
        /// Enum General for value: general
        /// </summary>
        [EnumMember(Value = "general")]
        General = 2
    }

}
