=begin
#Redocly Museum API

#Imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.

The version of the OpenAPI document: 1.2.1
Contact: team@redocly.com
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'date'
require 'time'

module OpenapiMuseumClient
  class TicketType
    EVENT = "event".freeze
    GENERAL = "general".freeze

    def self.all_vars
      @all_vars ||= [EVENT, GENERAL].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TicketType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TicketType"
    end
  end
end
