generatorName: java
additionalProperties:
  invokerPackage: org.openapitools.client
  apiPackage: org.openapitools.client.api
  modelPackage: org.openapitools.client.model
  artifactId: openapi-java-client
  hideGenerationTimestamp: true
  oseg.package: oseg.petstore.examples
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false
