/**
 * Redocly Museum API
 * Imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: team@redocly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TicketType } from './ticketType';

/**
* Data to purchase a ticket.
*/
export class BuyMuseumTickets {
    /**
    * Unique identifier for museum ticket. Generated when purchased.
    */
    'ticketId'?: string;
    'ticketDate': string;
    'ticketType': TicketType;
    /**
    * Identifier for a special event.
    */
    'eventId'?: string;
    /**
    * Email address for ticket purchaser.
    */
    'email'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ticketId",
            "baseName": "ticketId",
            "type": "string"
        },
        {
            "name": "ticketDate",
            "baseName": "ticketDate",
            "type": "string"
        },
        {
            "name": "ticketType",
            "baseName": "ticketType",
            "type": "TicketType"
        },
        {
            "name": "eventId",
            "baseName": "eventId",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BuyMuseumTickets.attributeTypeMap;
    }
}

export namespace BuyMuseumTickets {
}
