<?php
/**
 * TicketType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPIMuseum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Redocly Museum API
 *
 * Imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: team@redocly.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPIMuseum\Client\Model;
use \OpenAPIMuseum\Client\ObjectSerializer;

/**
 * TicketType Class Doc Comment
 *
 * @category Class
 * @description Type of ticket being purchased. Use &#x60;general&#x60; for regular museum entry and &#x60;event&#x60; for tickets to special events.
 * @package  OpenAPIMuseum\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TicketType
{
    /**
     * Possible values of this enum
     */
    public const EVENT = 'event';

    public const GENERAL = 'general';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EVENT,
            self::GENERAL
        ];
    }
}


