generatorName: php
additionalProperties:
  invokerPackage: "OpenAPI\\Client"
  packageName: openapi/client
  composerPackageName: openapi/client
  packageVersion: "1.0.0"
  artifactVersion: "1.0.0"
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false
oseg:
  namespace: OSEG\PetStore\Examples
  autoload_location: "__DIR__ . '/../vendor/autoload.php'"
