generatorName: php
additionalProperties:
  invokerPackage: "OpenAPI\\Client"
  packageName: openapi/client
  composerPackageName: openapi/client
  packageVersion: "1.0.0"
  artifactVersion: "1.0.0"
  oseg_namespace: OSEG\PetStore\Examples
  oseg_autoload_location: "__DIR__ . '/../vendor/autoload.php'"
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false
