generatorName: ruby
additionalProperties:
  gemName: openapimuseum_client
  moduleName: OpenApiMuseumClient
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false
