/*
 * Redocly Museum API
 * Imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: team@redocly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapimuseum.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapimuseum.client.JSON;

/**
 * Daily operating hours for the museum.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class MuseumDailyHours {
  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private LocalDate date;

  public static final String SERIALIZED_NAME_TIME_OPEN = "timeOpen";
  @SerializedName(SERIALIZED_NAME_TIME_OPEN)
  private String timeOpen;

  public static final String SERIALIZED_NAME_TIME_CLOSE = "timeClose";
  @SerializedName(SERIALIZED_NAME_TIME_CLOSE)
  private String timeClose;

  public MuseumDailyHours() {
  }

  public MuseumDailyHours date(LocalDate date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   */
  @javax.annotation.Nonnull
  public LocalDate getDate() {
    return date;
  }

  public void setDate(LocalDate date) {
    this.date = date;
  }


  public MuseumDailyHours timeOpen(String timeOpen) {
    this.timeOpen = timeOpen;
    return this;
  }

  /**
   * Time the museum opens on a specific date. Uses 24 hour time format (&#x60;HH:mm&#x60;).
   * @return timeOpen
   */
  @javax.annotation.Nonnull
  public String getTimeOpen() {
    return timeOpen;
  }

  public void setTimeOpen(String timeOpen) {
    this.timeOpen = timeOpen;
  }


  public MuseumDailyHours timeClose(String timeClose) {
    this.timeClose = timeClose;
    return this;
  }

  /**
   * Time the museum closes on a specific date. Uses 24 hour time format (&#x60;HH:mm&#x60;).
   * @return timeClose
   */
  @javax.annotation.Nonnull
  public String getTimeClose() {
    return timeClose;
  }

  public void setTimeClose(String timeClose) {
    this.timeClose = timeClose;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MuseumDailyHours museumDailyHours = (MuseumDailyHours) o;
    return Objects.equals(this.date, museumDailyHours.date) &&
        Objects.equals(this.timeOpen, museumDailyHours.timeOpen) &&
        Objects.equals(this.timeClose, museumDailyHours.timeClose);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, timeOpen, timeClose);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MuseumDailyHours {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    timeOpen: ").append(toIndentedString(timeOpen)).append("\n");
    sb.append("    timeClose: ").append(toIndentedString(timeClose)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("date");
    openapiFields.add("timeOpen");
    openapiFields.add("timeClose");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("date");
    openapiRequiredFields.add("timeOpen");
    openapiRequiredFields.add("timeClose");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MuseumDailyHours
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MuseumDailyHours.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MuseumDailyHours is not found in the empty JSON string", MuseumDailyHours.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MuseumDailyHours.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MuseumDailyHours` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MuseumDailyHours.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("timeOpen").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `timeOpen` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timeOpen").toString()));
      }
      if (!jsonObj.get("timeClose").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `timeClose` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timeClose").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MuseumDailyHours.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MuseumDailyHours' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MuseumDailyHours> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MuseumDailyHours.class));

       return (TypeAdapter<T>) new TypeAdapter<MuseumDailyHours>() {
           @Override
           public void write(JsonWriter out, MuseumDailyHours value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MuseumDailyHours read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MuseumDailyHours given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MuseumDailyHours
   * @throws IOException if the JSON string is invalid with respect to MuseumDailyHours
   */
  public static MuseumDailyHours fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MuseumDailyHours.class);
  }

  /**
   * Convert an instance of MuseumDailyHours to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

