/**
 * Redocly Museum API
 * Imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: team@redocly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Daily operating hours for the museum.
*/
export class MuseumDailyHours {
    'date': string;
    /**
    * Time the museum opens on a specific date. Uses 24 hour time format (`HH:mm`).
    */
    'timeOpen': string;
    /**
    * Time the museum closes on a specific date. Uses 24 hour time format (`HH:mm`).
    */
    'timeClose': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "timeOpen",
            "baseName": "timeOpen",
            "type": "string"
        },
        {
            "name": "timeClose",
            "baseName": "timeClose",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MuseumDailyHours.attributeTypeMap;
    }
}

