/**
 * Redocly Museum API
 * Imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: team@redocly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SpecialEventFields {
    /**
    * Name of the special event.
    */
    'name'?: string;
    /**
    * Location where the special event is held.
    */
    'location'?: string;
    /**
    * Description of the special event.
    */
    'eventDescription'?: string;
    /**
    * List of planned dates for the special event.
    */
    'dates'?: Array<string>;
    /**
    * Price of a ticket for the special event.
    */
    'price'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string"
        },
        {
            "name": "eventDescription",
            "baseName": "eventDescription",
            "type": "string"
        },
        {
            "name": "dates",
            "baseName": "dates",
            "type": "Array<string>"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SpecialEventFields.attributeTypeMap;
    }
}

