/*
 * Redocly Museum API
 *
 * Imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: team@redocly.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPIMuseum.Client;
using Org.OpenAPIMuseum.Model;

namespace Org.OpenAPIMuseum.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOperationsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get museum hours
        /// </summary>
        /// <remarks>
        /// Get upcoming museum operating hours.
        /// </remarks>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Starting date to retrieve future operating hours from. Defaults to today&#39;s date. (optional)</param>
        /// <param name="page">Page number to retrieve. (optional, default to 1)</param>
        /// <param name="limit">Number of days per page. (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;MuseumDailyHours&gt;</returns>
        List<MuseumDailyHours> GetMuseumHours(DateOnly? startDate = default(DateOnly?), int? page = default(int?), int? limit = default(int?), int operationIndex = 0);

        /// <summary>
        /// Get museum hours
        /// </summary>
        /// <remarks>
        /// Get upcoming museum operating hours.
        /// </remarks>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Starting date to retrieve future operating hours from. Defaults to today&#39;s date. (optional)</param>
        /// <param name="page">Page number to retrieve. (optional, default to 1)</param>
        /// <param name="limit">Number of days per page. (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;MuseumDailyHours&gt;</returns>
        ApiResponse<List<MuseumDailyHours>> GetMuseumHoursWithHttpInfo(DateOnly? startDate = default(DateOnly?), int? page = default(int?), int? limit = default(int?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOperationsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get museum hours
        /// </summary>
        /// <remarks>
        /// Get upcoming museum operating hours.
        /// </remarks>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Starting date to retrieve future operating hours from. Defaults to today&#39;s date. (optional)</param>
        /// <param name="page">Page number to retrieve. (optional, default to 1)</param>
        /// <param name="limit">Number of days per page. (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;MuseumDailyHours&gt;</returns>
        System.Threading.Tasks.Task<List<MuseumDailyHours>> GetMuseumHoursAsync(DateOnly? startDate = default(DateOnly?), int? page = default(int?), int? limit = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get museum hours
        /// </summary>
        /// <remarks>
        /// Get upcoming museum operating hours.
        /// </remarks>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Starting date to retrieve future operating hours from. Defaults to today&#39;s date. (optional)</param>
        /// <param name="page">Page number to retrieve. (optional, default to 1)</param>
        /// <param name="limit">Number of days per page. (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;MuseumDailyHours&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<MuseumDailyHours>>> GetMuseumHoursWithHttpInfoAsync(DateOnly? startDate = default(DateOnly?), int? page = default(int?), int? limit = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOperationsApi : IOperationsApiSync, IOperationsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class OperationsApi : IOperationsApi
    {
        private Org.OpenAPIMuseum.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="OperationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OperationsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OperationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OperationsApi(string basePath)
        {
            this.Configuration = Org.OpenAPIMuseum.Client.Configuration.MergeConfigurations(
                Org.OpenAPIMuseum.Client.GlobalConfiguration.Instance,
                new Org.OpenAPIMuseum.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPIMuseum.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPIMuseum.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPIMuseum.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OperationsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public OperationsApi(Org.OpenAPIMuseum.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPIMuseum.Client.Configuration.MergeConfigurations(
                Org.OpenAPIMuseum.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPIMuseum.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPIMuseum.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPIMuseum.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OperationsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public OperationsApi(Org.OpenAPIMuseum.Client.ISynchronousClient client, Org.OpenAPIMuseum.Client.IAsynchronousClient asyncClient, Org.OpenAPIMuseum.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPIMuseum.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPIMuseum.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPIMuseum.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPIMuseum.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPIMuseum.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get museum hours Get upcoming museum operating hours.
        /// </summary>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Starting date to retrieve future operating hours from. Defaults to today&#39;s date. (optional)</param>
        /// <param name="page">Page number to retrieve. (optional, default to 1)</param>
        /// <param name="limit">Number of days per page. (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;MuseumDailyHours&gt;</returns>
        public List<MuseumDailyHours> GetMuseumHours(DateOnly? startDate = default(DateOnly?), int? page = default(int?), int? limit = default(int?), int operationIndex = 0)
        {
            Org.OpenAPIMuseum.Client.ApiResponse<List<MuseumDailyHours>> localVarResponse = GetMuseumHoursWithHttpInfo(startDate, page, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get museum hours Get upcoming museum operating hours.
        /// </summary>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Starting date to retrieve future operating hours from. Defaults to today&#39;s date. (optional)</param>
        /// <param name="page">Page number to retrieve. (optional, default to 1)</param>
        /// <param name="limit">Number of days per page. (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;MuseumDailyHours&gt;</returns>
        public Org.OpenAPIMuseum.Client.ApiResponse<List<MuseumDailyHours>> GetMuseumHoursWithHttpInfo(DateOnly? startDate = default(DateOnly?), int? page = default(int?), int? limit = default(int?), int operationIndex = 0)
        {
            Org.OpenAPIMuseum.Client.RequestOptions localVarRequestOptions = new Org.OpenAPIMuseum.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = Org.OpenAPIMuseum.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPIMuseum.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (startDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPIMuseum.Client.ClientUtils.ParameterToMultiMap("", "startDate", startDate));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPIMuseum.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPIMuseum.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            localVarRequestOptions.Operation = "OperationsApi.GetMuseumHours";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (MuseumPlaceholderAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Org.OpenAPIMuseum.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<MuseumDailyHours>>("/museum-hours", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMuseumHours", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get museum hours Get upcoming museum operating hours.
        /// </summary>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Starting date to retrieve future operating hours from. Defaults to today&#39;s date. (optional)</param>
        /// <param name="page">Page number to retrieve. (optional, default to 1)</param>
        /// <param name="limit">Number of days per page. (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;MuseumDailyHours&gt;</returns>
        public async System.Threading.Tasks.Task<List<MuseumDailyHours>> GetMuseumHoursAsync(DateOnly? startDate = default(DateOnly?), int? page = default(int?), int? limit = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPIMuseum.Client.ApiResponse<List<MuseumDailyHours>> localVarResponse = await GetMuseumHoursWithHttpInfoAsync(startDate, page, limit, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get museum hours Get upcoming museum operating hours.
        /// </summary>
        /// <exception cref="Org.OpenAPIMuseum.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Starting date to retrieve future operating hours from. Defaults to today&#39;s date. (optional)</param>
        /// <param name="page">Page number to retrieve. (optional, default to 1)</param>
        /// <param name="limit">Number of days per page. (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;MuseumDailyHours&gt;)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPIMuseum.Client.ApiResponse<List<MuseumDailyHours>>> GetMuseumHoursWithHttpInfoAsync(DateOnly? startDate = default(DateOnly?), int? page = default(int?), int? limit = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Org.OpenAPIMuseum.Client.RequestOptions localVarRequestOptions = new Org.OpenAPIMuseum.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = Org.OpenAPIMuseum.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPIMuseum.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (startDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPIMuseum.Client.ClientUtils.ParameterToMultiMap("", "startDate", startDate));
            }
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPIMuseum.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPIMuseum.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            localVarRequestOptions.Operation = "OperationsApi.GetMuseumHours";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (MuseumPlaceholderAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Org.OpenAPIMuseum.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<MuseumDailyHours>>("/museum-hours", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetMuseumHours", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
